version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zoo
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9001:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tomcat:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: carrefour
    container_name: iam
    ports:
        - "9000:8080"
